# Generated by Django 5.2.4 on 2025-11-12 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_initial'),
        ('tenants', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='emergency_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='users.emergencycontact'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='id_proof_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='tenants.idprooftype'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='mailing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='users.address'),
        ),
        migrations.AddField(
            model_name='tenantunitassignment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_assignments', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tenantunitassignment',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_assignments', to='properties.unit'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['email'], name='tenants_email_64287b_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['phone_number'], name='tenants_phone_n_735d14_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['id_proof_type'], name='tenants_id_proo_9a6f6e_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['is_active'], name='tenants_is_acti_ec1713_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantunitassignment',
            index=models.Index(fields=['tenant'], name='tenant_unit_tenant__f271b0_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantunitassignment',
            index=models.Index(fields=['unit'], name='tenant_unit_unit_id_e10fbd_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantunitassignment',
            index=models.Index(fields=['is_current'], name='tenant_unit_is_curr_838da9_idx'),
        ),
    ]
