# Generated by Django 5.2.4 on 2025-11-12 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0002_initial'),
        ('maintenance', '0002_initial'),
        ('notifications', '0001_initial'),
        ('payments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='leases.lease'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_maintenance_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='maintenance.maintenancerequest'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='notifications.notificationtype'),
        ),
        migrations.AddField(
            model_name='reminderlog',
            name='delivery_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reminder_logs', to='notifications.deliverymethod'),
        ),
        migrations.AddField(
            model_name='reminderlog',
            name='reminder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.reminder'),
        ),
        migrations.AddField(
            model_name='reminderlog',
            name='sent_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminder_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reminders', to='notifications.remindertype'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient'], name='notificatio_recipie_1dd18d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_134aa2_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='notificatio_is_read_3f8c44_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx'),
        ),
        migrations.AddIndex(
            model_name='reminderlog',
            index=models.Index(fields=['reminder'], name='reminder_lo_reminde_eb3c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='reminderlog',
            index=models.Index(fields=['sent_to'], name='reminder_lo_sent_to_6c011a_idx'),
        ),
        migrations.AddIndex(
            model_name='reminderlog',
            index=models.Index(fields=['delivery_method'], name='reminder_lo_deliver_e885fa_idx'),
        ),
        migrations.AddIndex(
            model_name='reminderlog',
            index=models.Index(fields=['status'], name='reminder_lo_status_d724c7_idx'),
        ),
        migrations.AddIndex(
            model_name='reminderlog',
            index=models.Index(fields=['sent_at'], name='reminder_lo_sent_at_cf6725_idx'),
        ),
    ]
