# Generated by Django 5.2.4 on 2025-11-12 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0001_initial'),
        ('properties', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to='properties.unit'),
        ),
        migrations.AddField(
            model_name='maintenancerequestimage',
            name='maintenance_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='maintenance.maintenancerequest'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to='maintenance.maintenancestatus'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to='maintenance.priority'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequestimage',
            index=models.Index(fields=['maintenance_request'], name='maintenance_mainten_96c839_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['tenant'], name='maintenance_tenant__dde1e0_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['unit'], name='maintenance_unit_id_fc12da_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['priority'], name='maintenance_priorit_532b65_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['status'], name='maintenance_status__23c655_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['assigned_to'], name='maintenance_assigne_c6088e_idx'),
        ),
    ]
