# Generated by Django 5.2.4 on 2025-11-12 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='users.address'),
        ),
        migrations.AddField(
            model_name='building',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_buildings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='building',
            name='building_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buildings', to='properties.buildingtype'),
        ),
        migrations.AddField(
            model_name='unit',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='units', to='properties.amenity'),
        ),
        migrations.AddField(
            model_name='unit',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.building'),
        ),
        migrations.AddField(
            model_name='unitimage',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.unit'),
        ),
        migrations.AddField(
            model_name='unit',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='properties.unitstatus'),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='properties.unittype'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['address'], name='buildings_address_3be999_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['building_type'], name='buildings_buildin_adf909_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['owner'], name='buildings_owner_i_2fa6d1_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['is_active'], name='buildings_is_acti_1def2d_idx'),
        ),
        migrations.AddIndex(
            model_name='unitimage',
            index=models.Index(fields=['unit'], name='unit_images_unit_id_71738c_idx'),
        ),
        migrations.AddIndex(
            model_name='unitimage',
            index=models.Index(fields=['is_primary'], name='unit_images_is_prim_c2cc3a_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['building'], name='units_buildin_a3e5da_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['unit_type'], name='units_unit_ty_48fb6e_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['status'], name='units_status__41a449_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['unit_number'], name='units_unit_nu_24b15f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('building', 'unit_number')},
        ),
    ]
