# Generated by Django 5.2.4 on 2025-11-12 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0002_initial'),
        ('payments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_history_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentmethod'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='status_after',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_histories_after', to='payments.paymentstatus'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='status_before',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_histories_before', to='payments.paymentstatus'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentstatus'),
        ),
        migrations.AddField(
            model_name='rentschedule',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_schedules', to='leases.lease'),
        ),
        migrations.AddField(
            model_name='rentschedule',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rent_schedules', to='payments.paymentstatus'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['payment'], name='payment_his_payment_8ae8b6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['changed_at'], name='payment_his_changed_f040a5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['lease'], name='payments_lease_i_bbeb30_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant'], name='payments_tenant__d18216_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method'], name='payments_payment_d03ee0_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_status'], name='payments_payment_4273d5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['due_date'], name='payments_due_dat_ff319d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='payments_payment_aebcb7_idx'),
        ),
        migrations.AddIndex(
            model_name='rentschedule',
            index=models.Index(fields=['lease'], name='rent_schedu_lease_i_4c3c5e_idx'),
        ),
        migrations.AddIndex(
            model_name='rentschedule',
            index=models.Index(fields=['due_date'], name='rent_schedu_due_dat_020c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='rentschedule',
            index=models.Index(fields=['status'], name='rent_schedu_status__fd6a70_idx'),
        ),
    ]
