# Generated by Django 5.2.4 on 2025-11-12 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='related_lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='leases.lease'),
        ),
    ]
