# Generated by Django 5.2.4 on 2025-11-12 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0004_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documenttype'),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='documents', to='documents.tag'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='documents_documen_0426e4_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['related_lease'], name='documents_related_a61928_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['related_tenant'], name='documents_related_5cc007_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['related_unit'], name='documents_related_23e141_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_by'], name='documents_uploade_aad805_idx'),
        ),
    ]
