# Generated by Django 5.2.4 on 2025-11-12 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0001_initial'),
        ('properties', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='lease',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='properties.unit'),
        ),
        migrations.AddField(
            model_name='leaserenewal',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='leases.lease'),
        ),
        migrations.AddField(
            model_name='lease',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='leases.leasestatus'),
        ),
        migrations.AddField(
            model_name='lease',
            name='lease_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='leases.leasetype'),
        ),
        migrations.AddField(
            model_name='leaserenewal',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewals', to='leases.renewalstatus'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['tenant'], name='leases_tenant__c311df_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['unit'], name='leases_unit_id_723755_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['lease_type'], name='leases_lease_t_f63b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['status'], name='leases_status__39d0c7_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['end_date'], name='leases_end_dat_c6aab1_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['start_date'], name='leases_start_d_17e008_idx'),
        ),
        migrations.AddIndex(
            model_name='leaserenewal',
            index=models.Index(fields=['lease'], name='lease_renew_lease_i_4bc038_idx'),
        ),
        migrations.AddIndex(
            model_name='leaserenewal',
            index=models.Index(fields=['status'], name='lease_renew_status__7e6d0d_idx'),
        ),
        migrations.AddIndex(
            model_name='leaserenewal',
            index=models.Index(fields=['renewal_date'], name='lease_renew_renewal_266eca_idx'),
        ),
    ]
